apiVersion: {{ .Values.apiVersion }}
kind: AlertmanagerConfig
metadata:
  name: {{ include "alertmanager-config.fullname" . }}
  labels:
    {{- include "alertmanager-config.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- with (omit .Values.alertmanagerConfig "receivers" "route") }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with (include "alertmanager-config.receivers" .) }}
  {{- . | nindent 2 }}
{{- end }}
{{- with (required "Missing required alertmanagerConfig.route" .Values.alertmanagerConfig.route) }}
  route:
    receiver: {{ required "Missing receiver for root route." .receiver | quote }}
    {{- toYaml (omit . "receiver" "routes") | nindent 4 }}
  {{- with .routes }}
    {{- include "alertmanager-config.routes" $ | nindent 4 }}
  {{- end }}
{{- end }}
