{{- if .Values.alertmanagerTemplates.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager-config.fullname" . }}
  labels:
    {{- include "alertmanager-config.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  all: |-
  {{- $templates := omit .Values.alertmanagerTemplates "enabled" "templatesEnabledByDefault" -}}
  {{- range $templateName, $templateValues := $templates -}}
    {{- if or $templateValues.enabled (and (typeIs "<nil>" $templateValues.enabled) $.Values.alertmanagerTemplates.templatesEnabledByDefault) -}}
      {{- with $templateValues.templateString -}}
        {{- . | nindent 4 }}
      {{- end }}
      {{- if $templateValues.includeHelmTemplate }}
        {{- include (print "alertmanager-config.templates." $templateName) $ | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- range $templateName, $templateValues := $templates -}}
    {{- if or $templateValues.enabled (and (typeIs "<nil>" $templateValues.enabled) $.Values.alertmanagerTemplates.templatesEnabledByDefault) -}}
    {{- $templateName | nindent 2 }}: |-
      {{- with $templateValues.templateString -}}
        {{- . | nindent 4 }}
      {{- end }}
      {{- if $templateValues.includeHelmTemplate }}
        {{- include (print "alertmanager-config.templates." $templateName) $ | nindent 4 }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
